feat: Optimize script

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -55,33 +55,35 @@ jobs:
           echo "ETH_4337_ACCOUNT=${{ vars[format('{0}_ETH_4337_ACCOUNT', env.PREFIX)] }}" >> $GITHUB_ENV
           echo "ETHEREUM_PRIVATE_KEY=${{ secrets[format('{0}_ETHEREUM_PRIVATE_KEY', env.PREFIX)] }}" >> $GITHUB_ENV
           echo "POLYGON_PRIVATE_KEY=${{ secrets[format('{0}_POLYGON_PRIVATE_KEY', env.PREFIX)] }}" >> $GITHUB_ENV
+
       - name: Run Forge build
         run: |
           forge --version
           forge build --sizes
-        
-      - name: Run Forge tests
-        run: forge test -vvv
 
-      - name: Run coverage
+      - name: Run tests and coverage
         run: |
-          forge coverage --report lcov
-          forge coverage --report summary
+          TEST_RESULT=0
+          forge test -vvv || TEST_RESULT=$?
+          
+          if [ $TEST_RESULT -eq 0 ]; then
+            echo "Tests passed"
+            forge coverage --report lcov
+            forge coverage --report summary
+          else
+            echo "Tests failed"
+          fi
 
       - name: Check test results
         if: github.event_name == 'pull_request'
         run: |
-          if forge test -vvv; then
+          if [ ${{ steps.run_tests_and_coverage.outcome }} == "success" ]; then
             echo "Tests passed"
             exit 0
           else
             echo "Tests failed"
+            gh pr comment "$PR_URL" --body "Tests failed. Please fix the issues before merging."
             exit 1
           fi
-
-      - name: Set pull request status
-        if: github.event_name == 'pull_request' && failure()
-        run: |
-          gh pr comment "$PR_URL" --body "Tests failed. Please fix the issues before merging."
         env:
           PR_URL: ${{ github.event.pull_request.html_url }}
